(define (plural wd)
(if (equal? (last wd) 'y)
    (if (vowel? (last (bl wd)))
        (word wd 's)
        (word (bl wd) 'ies))
    (word wd 's)))

(define (vowel? letter)
    (member? letter '(a e i o u)))

(define (squaresums a b c)
    (if (>= a b)
        (if (>= b c)
            (+ (square a) (square b))
            (+ (square a) (square c)))
    (if (>= a c)
        (+ (square a) (square b))
        (+ (square b) (square c)))))

(define (square x)
    (* x x))